# BOT CONFIGURATION OPTIONS

# REQUIRED
token: <your token>
polling_delay: 5
rates_channel_id: <channel to post rates in>
bans_channel_id: <channel to post bans in>

# OPTIONAL
allowed_roles: <roles permitted to use bot commands>
rates_url: "http://arkdedicated.com/dynamicconfig.ini"
bans_url: "http://arkdedicated.com/bansummary.txt"