name: Main CI Workflow
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
        with: 
            cache: 'pip'
            cache-dependency-path: |
              setup.py
              requirements.dev.txt
      - run: pip install -r requirements.dev.txt .
      - run: pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
        with: 
            cache: 'pip'
            cache-dependency-path: |
              setup.py
              requirements.dev.txt
      - run: pip install -r requirements.dev.txt .
      - name: Run Black Linting
        run: black ark_discord_bot tests
