name: Main CI Workflow
on: 
  pull_request:
  push:
    branches: 
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
        with: 
            cache: 'pip'
            cache-dependency-path: |
              setup.py
              requirements.dev.txt
      - run: pip install -r requirements.dev.txt .
      - run: pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
        with: 
            cache: 'pip'
            cache-dependency-path: |
              setup.py
              requirements.dev.txt
      - run: pip install -r requirements.dev.txt .
      - name: Run Black Linting
        run: black --check ark_discord_bot tests
  semantic-release-python:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' # if main branch, assume triggered by push 
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Semantic Release 
        uses: cycjimmy/semantic-release-action@v2.6.0
        with: 
          semantic_version: 18
          extra_plugins: |
            @semantic-release/exec@v6
          branches: "[ main ]"
  publish-non-release-python:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
        with: 
          cache: 'pip'
          cache-dependency-path: |
            setup.py
            requirements.dev.txt
      - run: pip install -r requirements.dev.txt .
      - name: Build non-release
        run: |
          make python-build
      - name: Publish to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

